blank_issues_enabled: false
contact_links:
  - name: School IT Department
    url: mailto:it@mergington.edu
    about: Contact the IT department for account-related issues or technical problems that need immediate attention